<?php
/** Autogenerated on 2018-12-05 21:29 */

/** Section: MySQL */
define('DB_NAME', 'kanbans');
define('DB_USER', 'kanbans');
define('DB_PASS', 'passforkanbans');
define('DB_HOST', 'localhost');

/** End of autogenerated config file */
