#!/bin/sh

OUT_FILE=config.php

OpenFile() {
    echo '<?php' > $OUT_FILE
    echo "/** Autogenerated on `date +'%F %R'` */" >> $OUT_FILE
}

CompleteFile() {
    echo >> $OUT_FILE
    echo '/** End of autogenerated config file */' >> $OUT_FILE
}

NewSection() {
    echo >> $OUT_FILE
    echo "/** Section: $1 */" >> $OUT_FILE
}

Escape() {
    # Use this script to escape PHP strings.
    php -r "$(printf "echo addslashes(<<<'EOT'\n%s\nEOT\n);\n" "$1")"
}

Define() {
    printf "define('%s', '%s');\n" "$1" "$(Escape "$2")" >> $OUT_FILE
}

Prompt() {
    printf '%s [%s]: ' "$3" "$2"
    read value
    value="${value:=$2}"
    Define "$1" "$value"
}

PromptHidden() {
    printf '%s: ' "$2"
    read -s value
    echo
    value="${value:=}"
    Define "$1" "$value"
}

OpenFile

NewSection 'MySQL'
Prompt       DB_NAME 'kanbans'   'Database name'
Prompt       DB_USER 'kanbans'   'Database user name'
PromptHidden DB_PASS             'Database user password'
Prompt       DB_HOST 'localhost' 'Database hostname'

CompleteFile

echo
echo "# Configuration written in $OUT_FILE."
echo "# Move it to its appropriate directory to finish."
