<?php
/** Autogenerated on 2018-12-04 12:33 */

/** Section: MySQL */
define('DB_NAME', 'kanbans');
define('DB_USER', 'kanbans');
define('DB_PASS', '');
define('DB_HOST', 'localhost');

/** End of autogenerated config file */
